language: java

jdk:
  - oraclejdk8

before_install:
  - nvm install "6.10.3"
  - gem install compass

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start